version: '3'
services:
  auth_microservice:
    build:
      context: ./server
      dockerfile: /microservices/auth_microservice/Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
      - nats
  gateway:
    build:
      context: ./server
      dockerfile: /microservices/gateway_microservice/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - nats
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  nats:
    container_name: "nats"
    image: nats
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
networks:
  app-network:
    driver: bridge