env: "local"
http_server:
  address: "localhost:3002"
  timeout: "4s"
  idle_timeout: "60s"
database:
  host: "db"
  user: "gorm"
  password: "postgres"
  dbname: "main"
  port: 5432
storage_path: "files"
