env: "local"
http_server:
  address: "localhost:3002"
  timeout: "4s"
  idle_timeout: "60s"
database:
  host: "localhost"
  user: "gorm"
  password: "gorm"
  dbname: "main"
  port: 8000
storage_path: "files"
