env: "local"
http_server:
  address: "localhost:3002"
  timeout: "4s"
  idle_timeout: "60s"
database:
  host: "localhost"
  user: "postgres"
  password: "1234"
  dbname: "homekiller"
  port: 5432
storage_path: "files"
